### PR TITLE
Added support for missing Obj-related endpoints

### PR DESCRIPTION
**Pull request by ezilber-akamai**
## 📝 Description

Added support for the `GET object-storage/buckets/$1/$2/object-list` endpoint. Also reran some fixtures that were not properly sanitized.

## ✔️ How to Test

`make testunit`
`make testint`

### CODE REVIEW

**Review by yec-akamai — APPROVED** [review]
Tests passed locally!

**Comment by zliang-akamai** [comment]
Can we use Google's `go-querystring` library to simplified query string generation? I think this would be much safer than implementing it in-house.

**Comment by ezilber-akamai** [comment]
> Can we use [Google's `go-querystring`](https://github.com/google/go-querystring) library to simplified query string generation? I think this would be much safer than implementing it in-house.

Good idea! This is fixed now.

**Review by zliang-akamai — APPROVED** [review]
Looks good and works well to me, nice job!

**Pull request merged**
