### PR TITLE
new: Add cross repo testing for Release

### PR DESCRIPTION
**Pull request by ykim-1**
## 📝 Description

There is a need to run Terraform integration tests before releasing Linodego to ensure there are no breaking changes. 

Purpose: Automate testing for terraform in linodego repo using the latest code available
Trigger: manually triggered
Job:

Environment: Ubuntu
Steps:
- Checkout linodego repository
- Set up Go
- Update system packages
- Install system dependencies
- Checkout terraform-provider-linode repository
- Install linodego from source
- Install dependencies
- Run tests

## ✔️ How to Test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run the relevant unit/integration tests?**

## 📷 Preview

**If applicable, include a screenshot or code snippet of this change. Otherwise, please remove this section.**

### CODE REVIEW

**Comment by ykim-1** [comment]
Worked on my forked repository
https://github.com/ykim-1/linodego/actions/runs/8255232492/job/22581225109

**Review by yec-akamai — APPROVED** [review]
Nice work!

Can we add the manually triggering steps to the linodego release doc in [KB](https://kb.linode.com/display/Development/linodego)?

**Comment by ykim-1** [comment]
> Nice work!
> 
> Can we add the manually triggering steps to the linodego release doc in [KB](https://kb.linode.com/display/Development/linodego)?

Good idea I will do that before merging this in

**Review by lgarber-akamai — APPROVED** [review]
Works nicely on my fork, excellent work!

https://github.com/lgarber-akamai/linodego/actions/runs/8328688720/job/22789382672

**Pull request merged**
