### PR TITLE
Migrated nodebalancer_firewalls to object_storage_clusters to request helpers

### PR DESCRIPTION
**Pull request by ezilber-akamai**
## 📝 Description

Migrated nodebalancer_firewalls to object_storage_clusters to request helpers

### CODE REVIEW

**Comment by lgarber-akamai** [comment]
@ezilber-akamai Just a heads up, this PR might run into some conflicts with #522 depending on which one is merged first 👀

**Review by lgarber-akamai — APPROVED** [review]
Tests are passing on my end, great work!

**Review by ykim-1 — APPROVED** [review]
LGTM, tests all pass with new fixtures

**Review by lgarber-akamai — APPROVED** [review]
Looks great and tests seem to be passing, nice work!

**Pull request merged**
