### PR TITLE
Dropped `LongviewSubscription` from `AccountSettingsUpdateOptions`

### PR DESCRIPTION
**Pull request by ezilber-akamai**
## 📝 Description

Dropped `LongviewSubscription` from `AccountSettingsUpdateOptions`.

### CODE REVIEW

**Comment by yec-akamai** [comment]
Why do we need to remove `LongviewSubscription` from the update options? It seems `longview_subscription` is still available in the api doc https://www.linode.com/docs/api/account/#account-settings-update

**Comment by ezilber-akamai** [comment]
> Why do we need to remove `LongviewSubscription` from the update options? It seems `longview_subscription` is still available in the api doc https://www.linode.com/docs/api/account/#account-settings-update

According to the [ticket description](https://jira.linode.com/browse/TPT-2015) `LongviewSubscription` can no longer be updated through this endpoint.

**Review by yec-akamai — APPROVED** [review]

**Comment by lgarber-akamai** [comment]
Just to add a bit of context, this field can no longer be sent to the API since the API now returns the following error if `longview_subscription` is specified: 
```
longview_subscription editing at this location is no longer available. Please use the /longview/plan endpoint instead.
```

It might still be worth keeping the field to prevent introducing a breaking change for downstream consumers, but it might be worth considering to notify users of the non-functional endpoint. Does anyone have any thoughts on this? 🙂

**Comment by yec-akamai** [comment]
Maybe we can highlight this change in the corresponding release and let the user know the potential breaking change or the API doesn't work this way anymore. I'm also thinking we should let the API doc team know and update the doc as well to reduce confusion.

**Comment by ezilber-akamai** [comment]
I agree that we should probably keep the field to avoid any breaking changes, and I think adding a note to the release is a great idea!

**Pull request merged**
